version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    ports:
      - '8545:8545'
    command: '-h 0.0.0.0 -i 5777 --chainId 5777'
  vdg-api-accounting:
    image: javmo94/vdg-api-accounting:develop
    ports:
      - '4000:4000'
    environment: # Añade la sección environment
      - RPC_HOST=ganache
      - RPC_PORT=8545
      - GAS=4500000
      - GAS_PRICE=10000000000
      - PORT=4000
      - INITIAL_SUPPLY=99999999999999999999999999999999999999999999999999999999
    depends_on:
      - ganache







